%This program is free software; you can redistribute it and/or
%modify it under the terms of the GNU General Public License.
%
%This program is distributed in the hope that it will be useful,
%but WITHOUT ANY WARRANTY; without even the implied warranty of
%MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%GNU General Public License for more details.
%


%  This function reads in the bowtie alignments in '.bow' format in the
%  user-specified file 'bowtieFileName', and uses it to generate the small
%  RNA sequence read coverage of the genome described by 'genomeFileName'
%  and 'genomeVariableName'.  The bowtie alignment file can be the same as
%  used to generate the read alignments, but it need not be.  For example,
%  a user may wish to filter out highly repetitive small RNA sequences from
%  the alignments for putative miRNAs, but should retain them for
%  determining genome coverage.  The coverage variable generated by this
%  function will be used to compute Shannon Entropy for each small RNA
%  sequence read and known miRNA in the compuateShannonEntropy function.

function [coverage] = generateStartSiteCoverage(bowtieFileName, genomeFileName, genomeVariableName)
genome = load(genomeFileName, genomeVariableName);
genome = genome.(genomeVariableName);
for i=1:length(genome)
    Xsomemap.(genome(i).Header) = i;
end
coverage = [];
for i=1:length(genome)
    coverage(i).Header = genome(i).Header;
    coverage(i).coverage = zeros(1, length(genome(i).Sequence));
end
clear genome
%Allocated coverage

fid = fopen(bowtieFileName, 'r');
if (fid == -1)
    error('First input argument must be the name of the Bowtie output file')
end

while (~feof(fid))
    currentLine = fgetl(fid);
    currentCols = textscan(currentLine, '%s', 'delimiter', '\t', 'MultipleDelimsAsOne', 1);
    currentXsome = char(currentCols{1}(3));
    currentXsomeIndex = Xsomemap.(currentXsome);
    currentStart = str2double(char(currentCols{1}(4))) + 1;%+1 to translate from Bowtie's zero-based system, to MATLAB's one-base.
    coverage(currentXsomeIndex).coverage(currentStart) = coverage(currentXsomeIndex).coverage(currentStart) + 1;
end
fclose(fid);